### ISSUE TITLE
[BUG] Widget/Window Height gets expanded by big font-size

### ISSUE THREAD

**Issue by VuiMuich** [elkowar/eww#193] opened 2021-06-20 09:37 UTC
## Describe the bug
When the font-size is kind of big, the height of the bar is expanded.

But I guess this might be a 'known issue' actually, because the [widget documentation](https://elkowar.github.io/eww/main/widget-documentation/) state this is not possible:
> width: float width of this element. note that this can not restrict the size if the contents stretch it
height: float height of this element. note that this can not restrict the size if the contents stretch it

So if you feel this is more of a feature request, I'll surely adjust this issue accordingly.

## Reproducing the issue
Set both the height for a `bar` window and the font size for some `label` or `button` to `34px`.
The  size of the window is extended beyond 34px.
For comparison you could change the font size to something really small like `10px` to see the box shrink to its configured size of `34px`

## Expected behaviour
I would expect the window-size to stay fixed unless I provide a config flag `auto-scale: true` or something.

## Use Case
I want to use some Nerd-Font glyphs as labels, but they are very tiny in height, so clipping the white above and below the glyph would not matter.

I am affraid though, this might be a limitation by GTK with no easy way to work around.

**Comment by elkowar** [comment] 2021-06-22 19:53
yea, I fear this is generally a GTK limitation that _probably_ has some workaround, but one that I'm not currently aware of. If you find anything, then please do tell! This doesn't currently have super high priority for me, as it's moooostly work-aroundable by adding some hacks to the config, but I'd of course be open for a PR, and will otherwise look into these issues once the bigger things currently going on have been settled

**Comment by elkowar** [comment] 2021-07-15 12:19
Also, duplicate of #123 - closing

**Closed by elkowar** 2021-07-15 12:19 UTC
Labels: bug

**Comment by VuiMuich** [comment] 2021-07-15 16:49
Sorry for the dupe
