### ISSUE TITLE
[FEATURE] System Tray!

### ISSUE THREAD

**Issue by Oglo12** [elkowar/eww#720] opened 2023-03-23 16:04 UTC
### Description of the requested feature

A pretty and customizable system tray widget that can be placed in the bar or any other widget.

### Proposed configuration syntax

```
(systray :orientation "h"
               :class "systemtray"
               :iconsize "15px"
               :spacing "5px"
               :icontheme "Papirus Dark"
)
```

I can't think of any other syntax as I am very new to the whole Yuck configuration thing.

### Additional context

It would also be nice if it wasn't so hacked in like Polybar's where it floats as a separate bar above the bar.
Having the ability to set the icon colors and stuff would be nice. So the system tray could look nice with the color scheme.

**Comment by DiedByDisgust** [comment] 2023-03-23 21:32
Most delayed great feature ever. This could really boost the eww potential as a bar. Hope to see it sooner than later.

**Comment by VuiMuich** [comment] 2023-03-24 05:55
Have been running #676 for a couple of days now and it seems there is no glitches.

**Comment by elkowar** [comment] 2023-03-26 10:48
Closing this as a duplicate of #111. I'll be very happy once we have this in a fully usable state, yea -- don't worry, I feel y'all wanting this feature quite heavily.

**Closed by elkowar** 2023-03-26 10:48 UTC
Labels: enhancement
