### ISSUE TITLE
[BUG] Exclusive not taking effect 

### ISSUE THREAD

**Issue by EuanFH** [elkowar/eww#296] opened 2021-10-04 19:38 UTC
## Describe the bug
I have been trying to debug this for a couple of hours but at a bit of a loss.
From what i can gather exclusive is meant to make the window take up space on the screen and not float above it.
eww is setting the window as exclusive at least in the code(I break pointed on it) but the window manager is not respecting it.
The bar i am creating is floating over windows.
Here is my configuration for the bar
`
(defwindow bar
  :monitor 0
  :exclusive true
  :focusable false
  :stacking "fg"
  :geometry (geometry :x "0%"
                      :y "0%"
                      :width "20px"
                      :height "100%"
                      :anchor "left top")
  (river-bar))
`
I fully believe i could just be misunderstanding how to make this work in wayland but from reading the documentation this seems to be the correct way.

I have tried the bar out in both river and sway both have the same issue.

## Reproducing the issue
set exclusive to true in defwindow

## Expected behaviour
The tiling window manager respects the exclusive space and doesn't allow it to overlap with windows.

## Additional context
Image of window over lapping with bar:
![image](https://user-images.githubusercontent.com/2077938/135913145-bfb794ff-4065-4495-9a6e-1da091a90f34.png)
Full configuration files used:
[eww.scss.txt](https://github.com/elkowar/eww/files/7280800/eww.scss.txt)
[eww.yuck.txt](https://github.com/elkowar/eww/files/7280801/eww.yuck.txt)

**Comment by snakedye** [comment] 2021-10-06 10:08
There's a misunderstanding of exclusive. The compositor if windows are tiled will for the most part shift the position of tiled windows. It doesn't mean the region of the widget is completely forbidden. Change the stacking to bottom

**Comment by EuanFH** [comment] 2021-10-06 10:38
I updated it to look like this.
`(defwindow bar                                                                                                                                                                                                                                                                                                                                                                                                                         
  :monitor 0                                                                                                                                                                                                                                                                                                                                                                                                                           
  :exclusive true                                                                                                                                                                                                                                                                                                                                                                                                                      
  :focusable false                                                                                                                                                                                                                                                                                                                                                                                                                     
  :stacking "bottom"                                                                                                                                                                                                                                                                                                                                                                                                                   
  :geometry (geometry :x "0%"                                                                                                                                                                                                                                                                                                                                                                                                          
                      :y "0%"                                                                                                                                                                                                                                                                                                                                                                                                          
                      :width "20px"                                                                                                                                                                                                                                                                                                                                                                                                    
                      :height "100%"                                                                                                                                                                                                                                                                                                                                                                                                   
                      :anchor "left top")                                                                                                                                                                                                                                                                                                                                                                                              
  (river-bar))`

Still getting the issue as you can see in the image below.

@snakedye is there any chance you can provide and example window that will reserve the space.

![image](https://user-images.githubusercontent.com/2077938/136186761-2933ebe9-1ea9-4570-9462-632b542ee594.png)

**Comment by snakedye** [comment] 2021-10-06 11:30
```
(defwindow barleft
	:monitor 1
	:geometry (geometry :height "38px" :width "100%" :anchor "bottom center")
	:stacking "bt"
	:exclusive "true"
	(bar :tags {ristate.tags[1]}
		 :views {ristate.viewstag[1]})
)

```

**Comment by EuanFH** [comment] 2021-10-06 12:35
Aright after using your example as a test. I played about with the configuration.
It seems to be if you set the bar on the left or right anything other than center it will not reserve the space for the window.
This seems like a bug.

Works as expected
:geometry (geometry :height "20%" :width "20px" :anchor "left center")
:geometry (geometry :height "20%" :width "20px" :anchor "right center")

Broken:
:geometry (geometry :height "20%" :width "20px" :anchor "left top")
:geometry (geometry :height "20%" :width "20px" :anchor "left bottom")
:geometry (geometry :height "20%" :width "20px" :anchor "right top")
:geometry (geometry :height "20%" :width "20px" :anchor "right bottom")

**Comment by EuanFH** [comment] 2021-10-06 23:17
Yeah it seems to be the same issue for top and bottom as well.
center is the only option that will reserve space.

**Comment by elkowar** [comment] 2021-11-18 13:07
@EuanFH Ok so after some further research and discussion:
this _should_ work if you only had one window (i.e. you removed the clock window, and just showed the top left anchored bar.) That's obviously not the fix: If you want both, I'd recommend just going with making it one height 100% bar, and using something like `centerbox` to set the middle part as empty. That way you can avoid the weird case of having multiple `exclusive` windows attempt to be in the same place.

This _might_ just work in other compositors, as far as it got explained to me river here simply chooses to not reserve any space because you have multiple clients be exclusive and anchored to the left

**Comment by elkowar** [comment] 2022-05-21 13:17
Is this then just a general issue with layershell? As in, is this something eww could avoid? How does sway handle this with other bars, for example?

**Comment by EuanFH** [comment] 2022-06-11 18:59
[zwlr_layer_surface_v1::set_exclusive_zone](https://wayland.app/protocols/wlr-layer-shell-unstable-v1#zwlr_layer_surface_v1:request:set_exclusive_zone)
"A positive value is only meaningful if the surface is anchored to one edge or an edge and both perpendicular edges. If the surface is not anchored, anchored to only two perpendicular edges (a corner), anchored to only two parallel edges or anchored to all edges, a positive value will be treated the same as zero."

If I'm reading this right it seems to be that any configurations that aren't center would be invalid and be considered non exclusive.
Since i am assuming center is anchoring to the left and right or to top and bottom which would allow for exclusive to work.

**Comment by tpkee** [comment] 2022-07-07 16:24
Any update on this?

**Comment by snakedye** [comment] 2022-07-07 16:32
Basically this is not a bug. The protocol is just built that way.

**Comment by bekaertruben** [comment] 2022-08-12 16:03
I had this same issue and ended up being able to fix my bar using `:windowtype "dock"`.
According to the docks, this property is only supposed to do something on X11. However, on Hyprland no space is being reserved for my bar until I set it.

**Comment by elkowar** [comment] 2022-08-15 08:50
> I had this same issue and ended up being able to fix my bar using `:windowtype "dock"`. According to the docs, this property is only supposed to do something on X11. However, on Hyprland no space is being reserved for my bar until I set it.

Seems unlikely, given that the code only ever references WindowType::Dock in exactly one place, which is x11 specific ^^ I assume you also changed something else there?

Alternatively, you might be running eww using xwayland or something, lol

**Comment by elkowar** [comment] 2022-08-15 08:50
Anyways, given that this seems to be figured out (as per wayland-man snakedye <3), I'll close this issue for now!

**Closed by elkowar** 2022-08-15 08:50 UTC
Labels: bug

**Comment by bekaertruben** [comment] 2022-08-15 11:31
> Seems unlikely, given that the code only ever references WindowType::Dock in exactly one place, which is x11 specific ^^ I assume you also changed something else there?
> 
> Alternatively, you might be running eww using xwayland or something, lol

That's really weird indeed. The thing is, I've actually double-checked this, with changing just the one property. Additionally, I've checked that it is not running on xwayland. I'm using [eww-wayland-git](https://aur.archlinux.org/packages/eww-wayland-git), and xwininfo doesn't detect the window.
Moreover, when I run it on an X11 Plasma session, it _is_ detected by xwininfo (it is not on Plasma Wayland), but the bar appears in the center of the screen, presumably because I do not have any other X11 properties set:
```
(defwindow bar
  :monitor 0
  :exclusive true 
  :geometry (geometry 
    :height "1080px"
    :x "-4px" :y "0px"
    :width "52px"
    :anchor "left center"
  )
  :stacking "fg"
  :windowtype "dock"
(bar))
```

Maybe I should open a new issue for this, but I'm just playing around with eww for the first time, so there's too large a change I'm just doing something weird.

**Comment by ModProg** [comment] 2022-11-15 10:13
Can we get an error for this? i.e. for using `:exclusive true` without any of the valid anchors. Because while it seems to be the "expected" behavior of the protocol, it takes quite a while to figure out the solution.

**Comment by Preetam-Das** [comment] 2023-04-22 13:54
@elkowar so having this how should i go about making a left or right window. I am very new to eww so i don't know any hacky way of doing this (if there is any).

**Comment by sako-is** [comment] 2024-03-10 00:48
Hello, 
is there a solution for this yet? I'm having the same issue on Hyprland

**Comment by adsfibonacci** [comment] 2024-12-20 18:23
I had this working a while ago, but now it seems broken. I have the `top center` tag in the geometry its not respecting the exclusion. I've tried changing to other anchor types including those that I wasn't expecting to work, but it still overlaps with the window titles 

`(defwindow bar0 :monitor 0
               :geometry (geometry :x 0 :y 0 :height "15px" :width "80%" :anchor "top center")
               :stacking "bg"
         	:wm-ignore "true"
               :exclusive "true"
               :focusable "false"
  (bar0 :monitor "eDP-1"))`

**Comment by adsfibonacci** [comment] 2024-12-20 20:18
I had an issue with some xwayland bug. I did 
`export GDK_BACKEND=wayland` and `export WAYLAND_DISPLAY=wayland-1` which fixed it.
