### ISSUE TITLE
[BUG] eww doesn't wait until daemon is successfully launched

### ISSUE THREAD

**Issue by ahmedkhalf** [elkowar/eww#201] opened 2021-07-05 07:55 UTC
## Describe the bug

I have this in my i3 config:

```
exec_always --no-startup-id eww daemon
exec_always --no-startup-id eww open bar_window
```

eww starts the daemon but doesn't start the window

## Expected behaviour
I expect `eww daemon` to wait until it makes sure that the daemon is launched and can be connected to by the next command `eww open bar_window`

**Comment by undefinedDarkness** [comment] 2021-07-05 10:02
#142

**Comment by ahmedkhalf** [comment] 2021-07-05 10:10
The proposal of continously running 'eww open window' until its starts is a hack that works for now. But I think it should be fixed from the root.

**Comment by undefinedDarkness** [comment] 2021-07-05 10:14
Blame X or GTK not starting fast enough, idk

**Comment by snakedye** [comment] 2021-07-05 12:17
Doubt it's gtk, the issue is probably in how eww is initialized

**Comment by undefinedDarkness** [comment] 2021-07-05 16:41
Hmm maybe

**Comment by elkowar** [comment] 2021-07-05 20:38
it's both, lol. I'll definitely need to fix this. for now, there is also `eww ping` as a simple workaround

**Comment by undefinedDarkness** [comment] 2021-07-06 02:52
Lmao, Im always ready to blame gtk :)

**Comment by elkowar** [comment] 2021-08-18 15:19
Since the config rework, this is now fixed!
Now, eww will automatically start a daemon when you try to open a window and no daemon is running. Additionally, it will attempt to connect to the daemon a couple times before, thus giving it enough time to start in case it didn't initialize fully yet.

**Closed by elkowar** 2021-08-18 15:19 UTC
Labels: bug
