### ISSUE TITLE
[BUG] CSS background-image property is not rendering remote URL

### ISSUE THREAD

**Issue by arctic-bunny** [elkowar/eww#719] opened 2023-03-23 15:51 UTC
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I'm trying to render a background image with a remote source in a box widget. I followed this: https://github.com/elkowar/eww/issues/487 and I only get results if I use a local image. If I specify a URL, nothing is rendered.

### Reproducing the issue

```yuck
  (box 
      :style "background-image: url('${img_var}');"
      (label :text "My text here)
  )
```

If `img_var` is a local path, the image is rendered. If it's a URL, nothing is rendered.

### Expected behaviour

I expect the image to be rendered irrespective of the path being local or remote

**Comment by elkowar** [comment] 2023-03-26 10:44
Seems to work perfectly fine for me. Please make sure that your URL is actually valid and the image is reachable.
I'll close this for now as I can't reproduce, but If you have a minimal config example that demonstrates the issue reproducably, I'll be happy to look into it again!

**Closed by elkowar** 2023-03-26 10:44 UTC
Labels: bug

**Comment by arctic-bunny** [comment] 2023-03-26 17:34
Please try this config

```yuck
(defvar img_var "https://images.unsplash.com/photo-1507315991476-aece7be22af9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwcm9maWxlLXBhZ2V8Nnx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60")

(defwindow bar
  :monitor 0
  :windowtype "dock"
  :geometry (geometry :x "0%"
                      :y "0%"
                      :width "90%"
                      :height "20%"
                      :anchor "top center")
  :reserve (struts :side "top" :distance "4%")
  (box 
      :style "background-image: url('${img_var}'); background-size: cover;"
  )
)

```
![20230326192606](https://user-images.githubusercontent.com/120528122/227793301-5eb02c7e-16da-4cc8-ab89-9a2d7f51920b.png)

That's what I get with the config.

In my usecase, i'm trying to use album covers from spotify via playerctl. I tried checking with other players and I can get the thumbnail if i'm playing a video from youtube in firefox. I'm not sure what's happening. Seems like it happens by chance. I haven't managed to get any spotify image working though.

**Comment by Madeleaan** [comment] 2023-04-08 21:32
It works for firefox youtube videos, because firefox downloads the thumbnails into a local cache folder:
![image](https://user-images.githubusercontent.com/70163122/230743323-c34feba4-15fe-4408-82bc-4759d3959ecc.png)
