### ISSUE TITLE
[BUG] Stacking bg doesn't work in x11 i3

### ISSUE THREAD

**Issue by ahmedkhalf** [elkowar/eww#198] opened 2021-07-01 08:03 UTC
1. Set window option to stacking="bg"
2. eww daemon
3. eww open bar_window
4. make a window fullscreen
5. fullcreen window appears below bar

Config:
```xml
<eww>
    <includes>
        <!-- Put your <file>'s in here -->
    </includes>

    <definitions>
        <def name="desktop_switch_active">
            <button class="desktop-button-active">
                <label text="{{desktop_number}}"/>
            </button>
        </def>
        <def name="desktop_switch">
            <button class="desktop-button">
                <label text="{{desktop_number}}"/>
            </button>
        </def>
        <def name="bar">
            <box class="main-box-bar-window" space-evenly="false">
                <box class="right" halign="start" space-evenly="false">
                    <button class="search-button side-button">
                        <image path="./search_icon_2.png" height="18"/>
                    </button>
                    <literal valign="center" content="{{desktops}}"/>
                </box>
                <box class="middle" hexpand="true">
                    <label text="Todo: {{todo}}"/>
                </box>
                <box class="end" halign="end" space-evenly="false">

                    <button>
                        <label text="{{EWW_TEMPS.COMPOSITE}}°C"/>
                    </button>
                    <button>
                        <label text="{{EWW_BATTERY.BAT0.capacity}}%"/>
                    </button>
                    <button>
                        <label text="{{date}}"/>
                    </button>
                    <button class="search-button side-button">
                        <image path="./shutdown_icon.png" height="18"/>
                    </button>
                </box>

            </box>
        </def>
    </definitions>

    <variables>
        <script-var name="date" interval="5s">
        date "+%a %b %d %-I:%M %p"
        </script-var>
        <var name="desktops"></var>
        <var name="todo"/>
    </variables>

    <windows>
        <window name="bar_window" stacking="bg" focusable="false">
            <geometry anchor="top left" x="0" y="0" width="100%" height="40"/>
            <!-- <reserve side="top" distance="40px"/> -->
            <widget>
                <revealer transition="slidedown" duration="600ms" reveal="true">
                    <bar/>
                </revealer>
            </widget>
        </window>
    </windows>
</eww>

```

**Comment by elkowar** [comment] 2021-07-01 09:00
stacking has been pretty broken - duplicate of #178 and some others.

**Closed by elkowar** 2021-07-01 09:00 UTC
Labels: bug

**Comment by undefinedDarkness** [comment] 2021-07-01 09:16
making it focusable=true helps sometimes but eh thats 50/50

**Comment by thyeun** [comment] 2022-02-11 04:01
Sorry everyone, can i know stacking with i3 been fix, kindly clear my doubt (as i see this post been close)

Due to that, i still facing `:stacking "bg"` not working on i3, as you can see from the code below

```
;; Bar Windows ;;
(defwindow bar
	:geometry (geometry :x "0px" 
						:y "0px" 
						:height "1%" 
						:width "100%")
	:stacking "bg"
	:monitor 0					
	:reserve (struts :distance "0px" 
					 :side "bottom")
	:wm-ignore "false"
	:hexpand "false"
	:vexpand "false"
```
And even i include `:windowtype "dock"` it look like nothing change.
