### ISSUE TITLE
[FEATURE] Let Bindings

### ISSUE THREAD

**Issue by solomon-b** [elkowar/eww#942] opened 2023-10-02 16:53 UTC
### Description of the requested feature

`let` bindings allow you to bind a value to a locally scoped variable. They are super common in lisps and other functional programming languages. If we also had [functions](https://github.com/elkowar/eww/issues/430), especially if they could receive and produce widgets, then you start to a lot of power to dynamically build widgets.

### Proposed configuration syntax

```
(let [x 1] 
         x)
```
This would evaluate to `1`. 

```
(let [a 1 b 2] 
         {a + b })
```
This would evaluate to `3`.

**Comment by elkowar** [comment] 2023-12-11 09:42
Closing as a duplicate of #528  -- I'm still planning to have something like this, but it's more complex than it seems, sadly

**Closed by elkowar** 2023-12-11 09:42 UTC
Labels: enhancement
