### ISSUE TITLE
Could you please provide some examples?

### ISSUE THREAD

**Issue by ghistes** [elkowar/eww#307] opened 2021-10-16 00:07 UTC
Hi,

I've just spent some time with eww and I think it is a great project, however the documentation is extremely inadequate - especially for those (like myself) that have never done any gtk-programming.

So if you don't have the time to provide proper documentation could you at least provide some examples?

At the moment the projects you link to still use the old xml-config and so don't work at the moment while all you provide is one (ONE!!!!) example of a bar....

**Comment by elkowar** [comment] 2021-10-16 11:11
heres some more users configs: https://github.com/druskus20/dots/tree/master/eww/.config/eww
https://github.com/elkowar/dots-of-war/tree/master/eww-bar/.config/eww-bar

What do you find lacking in the current [documentation](https://elkowar.github.io/eww)? Some more concrete points would be helpful, so I know what to add

**Comment by Animeshz** [comment] 2021-10-20 12:40
One can easily find dotfiles repositories using eww :P with a google search maybe, or even reddit search...

**Comment by siduck76** [comment] 2021-10-23 00:52
> @siduck76 Isn't it what the guide already does?

its a bit confusing for normies like me :(

**Comment by elkowar** [comment] 2021-11-06 15:28
I'll close this for now, given that we recently added a couple more example configs to the readme!

**Closed by elkowar** 2021-11-06 15:28 UTC
Labels: documentation

**Comment by MostHated** [comment] 2022-01-19 23:04
> @ghistes I have a few examples [here](https://github.com/druskus20/eugh), mostly me playing around with revealers

I am not quite sure why, but only one of the examples in your repo worked for me (Revealer Hover Module). The rest ended up just showing boxes that did not do anything. I could see fluctuation in the process manager that some sort of activity was happening when mousing over, but it still just displayed an empty box.

**Comment by siduck** [comment] 2022-01-20 01:32
> > @ghistes I have a few examples [here](https://github.com/druskus20/eugh), mostly me playing around with revealers
> 
> I am not quite sure why, but only one of the examples in your repo worked for me (Revealer Hover Module). The rest ended up just showing boxes that did not do anything. I could see fluctuation in the process manager that some sort of activity was happening when mousing over, but it still just displayed an empty box.

same!

**Comment by siduck** [comment] 2022-01-20 01:33
@elkowar the input widget doesnt work properly, I wasnt able to type anything in it

**Comment by MostHated** [comment] 2022-01-20 02:24
I would need to test another one to be sure, but I believe the issue is that trying to use another config folder outside of the main default is basically more problem-causing than it is useful. I took the config files I had in there if the one that worked, put them in another folder and copied in just the files from another example instead of trying to do `eww -c /path/to/other/example`. I guess that is probably why only part of it showed up and worked. It feels like, if the example/config is not designed with being run from another folder to begin with, it doesn't seem to work. If it doesn't work/keep track of the config path that you pass to it when it starts, then I don't really understand why it even exists? Unless there is just more to it that I am not getting? Maybe making a wrapper to automatically reuse the first config you pass to it throughout the lifetime of the current executable, and if none, then use $HOME/.config/eww/ might help, but would just have to try it out and see. 

Either way, I guess, just put the files in the default place.
