### ISSUE TITLE
[BUG] Unable to install thorugh yay

### ISSUE THREAD

**Issue by lgtome** [elkowar/eww#841] opened 2023-07-07 00:09 UTC
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

I just wanted to install `eww` with `yay` and got an error during compiling:

```sh
error[E0635]: unknown feature `hash_drain_filter`
 --> crates/eww/src/main.rs:6:12
  |
6 | #![feature(hash_drain_filter)]
  |            ^^^^^^^^^^^^^^^^^

error[E0635]: unknown feature `drain_filter`
 --> crates/eww/src/main.rs:2:12
  |
2 | #![feature(drain_filter)]
  |            ^^^^^^^^^^^^

error[E0599]: no method named `drain_filter` found for struct `Vec<codespan_reporting::diagnostic::Label<usize>>` in the current scope
  --> crates/eww/src/error_handling_ctx.rs:55:23
   |
55 |     diagnostic.labels.drain_filter(|label| Span(label.range.start, label.range.end, label.file_id).is_du...
   |                       ^^^^^^^^^^^^ method not found in `Vec<Label<usize>>`

error[E0599]: no method named `drain_filter` found for struct `std::collections::HashMap` in the current scope
   --> crates/eww/src/widgets/widget_definitions.rs:130:62
    |
130 | ...s.unhandled_attrs.drain_filter(|a, _| deprecated.contains(&a.0 as &str)).collect();
    |                      ^^^^^^^^^^^^ method not found in `HashMap<AttrName, AttrEntry>`

Some errors have detailed explanations: E0599, E0635.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `eww` (bin "eww") due to 4 previous errors
==> ERROR: A failure occurred in build().
    Aborting...
```

### Reproducing the issue

- yay -Syu
- yay -S eww

### Expected behaviour

eww was installed correctly

### Additional context

All dependencies, rustc and cargo was installed.
- yay version: `yay v12.1.0 - libalpm v13.0.2`

**Comment by viandoxdev** [comment] 2023-07-07 06:20
Duplicate of #810.

**Comment by elkowar** [comment] 2023-07-29 19:22
I think you need to update your rust toolchain, also, just to say this again, the AUR package is _not_ officially maintained by me, although of course I'd love if it worked... lol

**Closed by elkowar** 2023-07-29 19:22 UTC
Labels: bug
