### ISSUE TITLE
[FEATURE] Support for multiline text on label widget

### ISSUE THREAD

**Issue by juacq97** [elkowar/eww#86] opened 2021-01-06 05:02 UTC
## Description of the requested feature
If I create a `label` widget or a `box` widget I can only put one-line text on it. So if I want to print a multiline text, like an output of a program, only the last line is printed.

## Proposed configuration syntax
There's no need... I think

# Additional context
Here you can see the output of `fortune` on the terminal and on a `label` widget. Notice how the widget only shows the last line of the STDOUT
![2021-01-05T21:56:56,688481467-07:00](https://user-images.githubusercontent.com/7623047/103730976-4e7bd780-4fa1-11eb-935f-52192a763289.png)

My `eww.xml` is here:

```xml
<eww>
    <definitions>
	<def name="fetch">
	    <box orientation="v" space-evenly="false">
		<label wrap="true" text="{{ufetch}}"/> 
	    </box>
	</def> 
  </definitions>

  <variables>
           <script-var name="ufetch"> fortune filosofia </script-var>
  </variables>

<windows>
    <window name="main_window" stacking="fg" focusable="false">
        <geometry anchor="top left" x="300px" y="50%" width="25%" height="300px"/>
        <widget>
		<fetch/>
        </widget>
    </window>
    </windows>
</eww>
```

**Comment by elkowar** [comment] 2021-01-06 13:21
Seems like a duplicate of #84 which has already been fixed. Are you on the current latest version?

**Comment by juacq97** [comment] 2021-01-06 21:42
> Are you on the current latest version?

Yes, just installed from AUR. If a create a `<var>` variable like this: 
```xml
      <var name="ufetch"> first-line \n second-line </var>
```
it prints as expected, but not if I pass the output from a CLI program. Maybe the escape sequence is different on those programs? I tried a simple `<script-var name="ufetch"> echo -e "first-line /n second-line" </script-var>` and the output was "first-line /n second-line".

**Comment by elkowar** [comment] 2021-01-16 15:27
Ahhhh. Well, looking at it more closely, this is expected behaviour:
You're using a script-var without an `interval`. that script-var will run once, and continuously listen for output, replacing the value every time a new line is printed.

If you want multiple lines, you'll need to provide an interval.

**Closed by elkowar** 2021-01-16 15:27 UTC
Labels: enhancement
