### ISSUE TITLE
[BUG] Parent does not resize when children get smaller

### ISSUE THREAD

**Issue by Robonics** [elkowar/eww#690] opened 2023-02-16 23:02 UTC
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

Whenever a child resizes, it will only resize the parents whenever it gets large, not when it gets smaller. If a text field (or any other element) grows, it's parent will expand to accommodate it, but if that element then gets shorter, the parent will no longer shrink. This is mainly a problem with variables that have inconsistent length.

### Reproducing the issue

The easiest way to see this is to use a label that contains something like a song or album name:
```yuck
(deflisten song_info :initial "Song - Artist"
  `playerctl metadata --format "{{title}} - {{artist}}" --follow`)

(defwindow song_box
	:monitor 0
	:geometry (geometry :x "15px"
	:y "15px"
	:anchor "top left")
	:stacking "bg"
	:windowtype "dock"
	:wm-ignore false
	:style "background-color: transparent;"
	(box
		:orientation "h"
		:space-evenly false
		(label :text "The current song is:")
		(label :text song_info :style "font-style: italic;")
	)
)
```
If a song or artist with a particularly long name shows up, it will stretch the entire box, and when the song changes back to something shorter, it will not re-shrink.

### Expected behaviour

The parent node should resize itself to just contain it's children without extra space after they get smaller.

### Additional context

Some research online leads me to believe that this is a GTK think more than an eww thing, but [SO post](https://stackoverflow.com/questions/8903140/shrink-window-in-gtk-dynamically-when-content-shrinks) post does mention a solution, no clue if said solution is applicable for EWW.

Some examples from my current setup:
Fine at first:
![Is Fine Initially](https://i.imgur.com/8NjOf8w.png)
Song with a long name plays:
![Parent gets larger with a long song](https://i.imgur.com/0chcfLi.png)
Ugly blank space that won't go away:
![Now there is all this ugly extra space](https://i.imgur.com/SXP1GYZ.png)

**Comment by elkowar** [comment] 2023-02-18 15:07
Duplicate of #193 and #123 -- I'm sure this is _somehow_ solvable, but so far all my attempts to implement it have failed :/.

**Closed by elkowar** 2023-02-18 15:07 UTC
Labels: bug
